Book store 1
HatimDev-HE/Awesome-books pull request #1
Opened 2022-07-04 13:04 UTC by HatimDev-HE

2022-07-04 14:49 UTC, AzizRAA commented
Style lint is empty there is no CSS required for today's project. Thats why Stylelint is showing error.

2022-07-04 15:46 UTC, FrederickMih requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 15:46 UTC, FrederickMih commented on index.js
> +    localStorage.setItem('books', JSON.stringify(books));
- [ ] Kindly make sure that books are preserved correctly in the browser's memory. When I reload the page after adding some books, all the books disappear. Let's fix this issue.

2022-07-05 09:25 UTC, HatimDev-HE commented on index.js
> +    localStorage.setItem('books', JSON.stringify(books));
Resolved this

2022-07-05 09:30 UTC, Deepakdanger approved these changes
**Hi @Team,** 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] In the Readme file, Kindly include the topic description & all authors details should be there.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 09:33 UTC, merged